name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update_resume:
    runs-on: ubuntu-latest
    name: main.yml work
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      - name: start action.yml
        uses: ./

      - run: git config --global user.email "ramusdmitry@gmail.com"
      - run: git config --global user.name "Dmitriy Ramus"
      - run: git add resume.pdf
      - run: git status
      - run: git commit -m "resume.pdf"
      - run: git push origin HEAD:main --force
      

