name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update_resume:
    runs-on: ubuntu-latest
    name: main.yml work
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      - name: start action.yml
        uses: ./

      - run: git config --global user.email "ramusdmitry@gmail.com"
      - run: git config --global user.name "Dmitriy Ramus"
      
      - run: git add -A
      - run: git status
      - run: git commit -m "resume.pdf"
      
      - run: git push origin HEAD:pages --force
      - run: git push origin HEAD:main --force
      
      - run: mkdir resume_result
      - run: ls -A; ls -d CV
      
      - run: mv resume.pdf resume_result/resume.pdf
      - run: mv index.html /resume_result/index.html      
      
      - name: Publish pdf
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: pages
          build_dir: resume_result
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
